image: node:8.11.3

stages:
  - build-and-deploy
  - purge-cache

build-and-deploy:
  stage: build-and-deploy
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
  only:
    - master

purge-cache:
  stage: purge-cache
  script:
    - curl -X POST https://api.cloudflare.com/client/v4/zones/71c9bd8afe5d090a95dad4560e3bb7a0/purge_cache -H 'Content-Type:application/json' -H 'Postman-Token:ca2c862e-45fe-410b-a532-8f58e0987355' -H 'X-Auth-Email:wat@hotmail.com' -H 'X-Auth-Key:971' -H 'cache-control:no-cache' -d '{"purge_everything":true}'
  only:
    - master
