stages:
  - build-and-deploy
  - purge-cache
  - deployment-alert

build-deploy:
  image: node:12.22.8
  stage: build-and-deploy
  script:
    - sudo apt-get update -y
    - sudo apt-get install -y nasm
    - yarn install
    - yarn gatsby build --prefix-paths
  artifacts:
    paths:
      - public
  only:
    - master
  environment:
    name: production
    url: https://edgardev.com

purge-cache:
  image: appropriate/curl
  stage: purge-cache
  script:
    - curl --fail -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_IDENTIFIER/purge_cache" -H "Content-Type:application/json" -H "X-Auth-Email:$CLOUDFLARE_AUTH_EMAIL" -H "X-Auth-Key:$CLOUDFLARE_AUTH_KEY" -H "cache-control:no-cache" -d '{"purge_everything":true}'
  only:
    - master

deployment-alert:
  image: appropriate/curl
  stage: deployment-alert
  script:
    -  curl --fail -X POST "$SLACK_WEBHOOK_URL" -H "Content-Type:application/json"  -d '{"channel":"#alerts","username":"GitlabCI","text":"Personal Blog Deployed successfully.","icon_emoji":":ghost:"}'
  only:
    - master



