image: node:8.14.0

stages:
  - build-and-deploy

pages:
  stage: build-and-deploy
  script:
    - npm install
    - npm install gatsby-cli
    - node_modules/.bin/gatsby build --prefix-paths
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
  only:
    - master

