image: alpine:latest

stages:
  - build
  - production

build:
  image: node:8.14.0-jessie-slim
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
  environment:
    name: production
    url: https://edgardev.com
  only:
    - master

.production: &production_template
  dependencies:
    - build
  stage: production
  script:
    - check_kube_domain
    - install_dependencies
    - download_chart
    - ensure_namespace
    - initialize_tiller
    - create_secret
    - deploy
    - delete canary
    - delete rollout
    - persist_environment_url
  environment:
    name: production
    url: http://$CI_PROJECT_PATH_SLUG.$AUTO_DEVOPS_DOMAIN
  artifacts:
    paths: [environment_url.txt]

production:
  <<: *production_template
  only:
    refs:
      - master
  except:
    variables:
      - $STAGING_ENABLED
      - $CANARY_ENABLED
      - $INCREMENTAL_ROLLOUT_ENABLED
      - $INCREMENTAL_ROLLOUT_MODE
      - $KUBECONFIG == null
