stages:
  - deploy
  - purge-cache
  - deployment-alert

# These folders are cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .cache/
    - public/

pages:
  image: node:12.22.8
  stage: deploy
  environment:
    name: production
    url: https://edgardev.com
  script:
    - apt-get update -y
    - apt-get install -y nasm
    - yarn install
    - yarn gatsby build
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

purge-cache:
  image: appropriate/curl
  stage: purge-cache
  script:
    - curl --fail -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_IDENTIFIER/purge_cache" -H "Content-Type:application/json" -H "X-Auth-Email:$CLOUDFLARE_AUTH_EMAIL" -H "X-Auth-Key:$CLOUDFLARE_AUTH_KEY" -H "cache-control:no-cache" -d '{"purge_everything":true}'
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deployment-alert:
  image: appropriate/curl
  stage: deployment-alert
  script:
    -  curl --fail -X POST "$SLACK_WEBHOOK_URL" -H "Content-Type:application/json"  -d '{"channel":"#alerts","username":"GitlabCI","text":"Personal Blog Deployed successfully.","icon_emoji":":ghost:"}'
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH



