stages:
  - build-and-deploy
  - purge-cache

build-and-deploy:
  image: node:8.14.0-jessie-slim
  stage: build-and-deploy
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
  only:
    - master

purge-cache:
  image: appropriate/curl
  stage: purge-cache
  script:
    - curl --fail -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_IDENTIFIER/purge_cache" -H "Content-Type:application/json" -H "X-Auth-Email:$CLOUDFLARE_AUTH_EMAIL" -H "X-Auth-Key:$CLOUDFLARE_AUTH_KEY" -H "cache-control:no-cache" -d '{"purge_everything":true}'
  only:
    - master
